import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { getInitials } from "@/utils/get-initials";
import { useSuspenseInfiniteQuery } from "@tanstack/react-query";
import { dayjs } from "@/lib/dayjs";
import { Calendar, Clapperboard, Video } from "lucide-react";
import { useParams } from "@tanstack/react-router";
import { z } from "zod";
import { useEffect, useRef } from "react";

type ProjectStatus = "ERROR" | "PROCESSING" | "SUCCESS" | "SCHEDULED";

export const projectsListSchema = z.object({
  projects: z.array(
    z.object({
      id: z.string(),
      title: z.string(),
      thumbnailUrl: z.string().nullable(),
      status: z.enum(["ERROR", "PROCESSING", "SUCCESS", "SCHEDULED"]),
      createdAt: z.date(),
      owner: z.object({
        name: z.string(),
        avatarUrl: z.string().nullable(),
      }),
      totalClips: z.number(),
    }),
  ),
  nextCursor: z.string().nullable(),
});

export function ProjectsList() {
  const loadMoreRef = useRef<HTMLDivElement>(null);
  const observerRef = useRef<IntersectionObserver>(null);

  const { slug } = useParams({
    from: "/dashboard/orgs/$slug",
  });

  const { data, hasNextPage, fetchNextPage, isFetchingNextPage } =
    useSuspenseInfiniteQuery({
      queryKey: ["projects"],
      queryFn: async ({ pageParam }) => {
        const url = new URL("http://localhost:8080/api/projects");

        if (pageParam) {
          url.searchParams.set("cursor", pageParam);
        }

        const response = await fetch(url);

        const data = await response.json();

        return projectsListSchema.parse(data);
      },
      getNextPageParam: (lastPage) => {
        return lastPage.nextCursor ?? undefined;
      },
      initialPageParam: undefined as string | undefined,
    });

  useEffect(() => {
    if (observerRef.current) {
      observerRef.current.disconnect();
    }

    observerRef.current = new IntersectionObserver(
      (entries) => {
        const entry = entries[0];

        if (entry.isIntersecting && hasNextPage && !isFetchingNextPage) {
          fetchNextPage();
        }
      },
      {
        threshold: 0.1,
      },
    );

    if (loadMoreRef.current) {
      observerRef.current.observe(loadMoreRef.current);
    }

    return () => {
      if (observerRef.current) {
        observerRef.current.disconnect();
      }
    };
  }, [hasNextPage, isFetchingNextPage, fetchNextPage]);

  const projects = data.pages.flatMap((page) => page.projects);

  const isProjectsEmpty = projects.length === 0;

  if (isProjectsEmpty) {
    return <p>Empty projects</p>;
  }

  function getProjectStatusBadge(projectStatus: ProjectStatus) {
    switch (projectStatus) {
      case "SUCCESS":
        return (
          <Badge className="absolute top-4 right-4" variant={"success"}>
            {projectStatus}
          </Badge>
        );
      case "ERROR":
        return (
          <Badge className="absolute top-4 right-4" variant={"destructive"}>
            {projectStatus}
          </Badge>
        );
      case "PROCESSING":
        return (
          <Badge className="absolute top-4 right-4" variant={"warning"}>
            {projectStatus}
          </Badge>
        );
    }
  }

  return (
    <div className="flex items-center gap-x-4 flex-wrap">
      {projects.map((project) => {
        return (
          <div key={project.id} className="size-[320px]">
            <header className="relative">
              {project.thumbnailUrl !== null ? (
                <img
                  className="rounded-t-lg w-[320px] h-[177px]"
                  src={project.thumbnailUrl}
                  alt={`${project.title} thumbnail`}
                />
              ) : (
                <div className="rounded-t-lg w-[320px] h-[177px] text-muted-foreground flex-col gap-y-2 bg-zinc-900 border border-input flex items-center justify-center">
                  <Clapperboard />
                  <p className="text-sm">
                    Clips generated by file has not thumbnail
                  </p>
                </div>
              )}
              {getProjectStatusBadge(project.status)}
            </header>

            <section className="space-y-4 px-[19px] py-[17px] border border-x-input">
              <h1 className="font-semibold">{project.title}</h1>

              <div className="flex items-center justify-between text-muted-foreground">
                <div className="flex items-center gap-x-2">
                  <Calendar />
                  <p>{dayjs(project.createdAt).from(new Date())}</p>
                </div>
                <div className="flex items-center gap-x-2">
                  <Video />
                  <p>{project.totalClips} Clips</p>
                </div>
              </div>
            </section>

            <footer className="flex items-center gap-x-2 px-[19px] py-2.5 rounded-b-lg bg-zinc-900 border border-input">
              <Avatar className="size-5">
                {project.owner.avatarUrl && (
                  <AvatarImage src={project.owner.avatarUrl} />
                )}
                <AvatarFallback>
                  {getInitials(project.owner.name)}
                </AvatarFallback>
              </Avatar>
              <p className="text-muted-foreground text-sm">
                Created by{" "}
                <span className="text-primary">{project.owner.name}</span>
              </p>
            </footer>
          </div>
        );
      })}
    </div>
  );
}
