/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as DashboardLayoutRouteImport } from './pages/dashboard/layout'
import { Route as IndexRouteImport } from './pages/index'
import { Route as DashboardOrgsIndexRouteImport } from './pages/dashboard/orgs/index'
import { Route as AuthSignUpIndexRouteImport } from './pages/auth/sign-up/index'
import { Route as AuthSignInIndexRouteImport } from './pages/auth/sign-in/index'
import { Route as DashboardOrgsSlugLayoutRouteImport } from './pages/dashboard/orgs/$slug/layout'
import { Route as DashboardOrgsSlugIndexRouteImport } from './pages/dashboard/orgs/$slug/index'
import { Route as DashboardOrgsSlugSettingsIndexRouteImport } from './pages/dashboard/orgs/$slug/settings/index'
import { Route as DashboardOrgsSlugProjectsIndexRouteImport } from './pages/dashboard/orgs/$slug/projects/index'
import { Route as DashboardOrgsSlugPostsIndexRouteImport } from './pages/dashboard/orgs/$slug/posts/index'
import { Route as DashboardOrgsSlugMembersIndexRouteImport } from './pages/dashboard/orgs/$slug/members/index'
import { Route as DashboardOrgsSlugIntegrationsIndexRouteImport } from './pages/dashboard/orgs/$slug/integrations/index'
import { Route as DashboardOrgsSlugPostsCreatePostsIndexRouteImport } from './pages/dashboard/orgs/$slug/posts/create-posts/index'

const DashboardLayoutRoute = DashboardLayoutRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgsIndexRoute = DashboardOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const AuthSignUpIndexRoute = AuthSignUpIndexRouteImport.update({
  id: '/auth/sign-up/',
  path: '/auth/sign-up/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInIndexRoute = AuthSignInIndexRouteImport.update({
  id: '/auth/sign-in/',
  path: '/auth/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrgsSlugLayoutRoute = DashboardOrgsSlugLayoutRouteImport.update({
  id: '/orgs/$slug',
  path: '/orgs/$slug',
  getParentRoute: () => DashboardLayoutRoute,
} as any)
const DashboardOrgsSlugIndexRoute = DashboardOrgsSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardOrgsSlugLayoutRoute,
} as any)
const DashboardOrgsSlugSettingsIndexRoute =
  DashboardOrgsSlugSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => DashboardOrgsSlugLayoutRoute,
  } as any)
const DashboardOrgsSlugProjectsIndexRoute =
  DashboardOrgsSlugProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => DashboardOrgsSlugLayoutRoute,
  } as any)
const DashboardOrgsSlugPostsIndexRoute =
  DashboardOrgsSlugPostsIndexRouteImport.update({
    id: '/posts/',
    path: '/posts/',
    getParentRoute: () => DashboardOrgsSlugLayoutRoute,
  } as any)
const DashboardOrgsSlugMembersIndexRoute =
  DashboardOrgsSlugMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => DashboardOrgsSlugLayoutRoute,
  } as any)
const DashboardOrgsSlugIntegrationsIndexRoute =
  DashboardOrgsSlugIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => DashboardOrgsSlugLayoutRoute,
  } as any)
const DashboardOrgsSlugPostsCreatePostsIndexRoute =
  DashboardOrgsSlugPostsCreatePostsIndexRouteImport.update({
    id: '/posts/create-posts/',
    path: '/posts/create-posts/',
    getParentRoute: () => DashboardOrgsSlugLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/orgs/$slug': typeof DashboardOrgsSlugLayoutRouteWithChildren
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/dashboard/orgs': typeof DashboardOrgsIndexRoute
  '/dashboard/orgs/$slug/': typeof DashboardOrgsSlugIndexRoute
  '/dashboard/orgs/$slug/integrations': typeof DashboardOrgsSlugIntegrationsIndexRoute
  '/dashboard/orgs/$slug/members': typeof DashboardOrgsSlugMembersIndexRoute
  '/dashboard/orgs/$slug/posts': typeof DashboardOrgsSlugPostsIndexRoute
  '/dashboard/orgs/$slug/projects': typeof DashboardOrgsSlugProjectsIndexRoute
  '/dashboard/orgs/$slug/settings': typeof DashboardOrgsSlugSettingsIndexRoute
  '/dashboard/orgs/$slug/posts/create-posts': typeof DashboardOrgsSlugPostsCreatePostsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/auth/sign-in': typeof AuthSignInIndexRoute
  '/auth/sign-up': typeof AuthSignUpIndexRoute
  '/dashboard/orgs': typeof DashboardOrgsIndexRoute
  '/dashboard/orgs/$slug': typeof DashboardOrgsSlugIndexRoute
  '/dashboard/orgs/$slug/integrations': typeof DashboardOrgsSlugIntegrationsIndexRoute
  '/dashboard/orgs/$slug/members': typeof DashboardOrgsSlugMembersIndexRoute
  '/dashboard/orgs/$slug/posts': typeof DashboardOrgsSlugPostsIndexRoute
  '/dashboard/orgs/$slug/projects': typeof DashboardOrgsSlugProjectsIndexRoute
  '/dashboard/orgs/$slug/settings': typeof DashboardOrgsSlugSettingsIndexRoute
  '/dashboard/orgs/$slug/posts/create-posts': typeof DashboardOrgsSlugPostsCreatePostsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardLayoutRouteWithChildren
  '/dashboard/orgs/$slug': typeof DashboardOrgsSlugLayoutRouteWithChildren
  '/auth/sign-in/': typeof AuthSignInIndexRoute
  '/auth/sign-up/': typeof AuthSignUpIndexRoute
  '/dashboard/orgs/': typeof DashboardOrgsIndexRoute
  '/dashboard/orgs/$slug/': typeof DashboardOrgsSlugIndexRoute
  '/dashboard/orgs/$slug/integrations/': typeof DashboardOrgsSlugIntegrationsIndexRoute
  '/dashboard/orgs/$slug/members/': typeof DashboardOrgsSlugMembersIndexRoute
  '/dashboard/orgs/$slug/posts/': typeof DashboardOrgsSlugPostsIndexRoute
  '/dashboard/orgs/$slug/projects/': typeof DashboardOrgsSlugProjectsIndexRoute
  '/dashboard/orgs/$slug/settings/': typeof DashboardOrgsSlugSettingsIndexRoute
  '/dashboard/orgs/$slug/posts/create-posts/': typeof DashboardOrgsSlugPostsCreatePostsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/orgs/$slug'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/orgs'
    | '/dashboard/orgs/$slug/'
    | '/dashboard/orgs/$slug/integrations'
    | '/dashboard/orgs/$slug/members'
    | '/dashboard/orgs/$slug/posts'
    | '/dashboard/orgs/$slug/projects'
    | '/dashboard/orgs/$slug/settings'
    | '/dashboard/orgs/$slug/posts/create-posts'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/dashboard/orgs'
    | '/dashboard/orgs/$slug'
    | '/dashboard/orgs/$slug/integrations'
    | '/dashboard/orgs/$slug/members'
    | '/dashboard/orgs/$slug/posts'
    | '/dashboard/orgs/$slug/projects'
    | '/dashboard/orgs/$slug/settings'
    | '/dashboard/orgs/$slug/posts/create-posts'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/orgs/$slug'
    | '/auth/sign-in/'
    | '/auth/sign-up/'
    | '/dashboard/orgs/'
    | '/dashboard/orgs/$slug/'
    | '/dashboard/orgs/$slug/integrations/'
    | '/dashboard/orgs/$slug/members/'
    | '/dashboard/orgs/$slug/posts/'
    | '/dashboard/orgs/$slug/projects/'
    | '/dashboard/orgs/$slug/settings/'
    | '/dashboard/orgs/$slug/posts/create-posts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardLayoutRoute: typeof DashboardLayoutRouteWithChildren
  AuthSignInIndexRoute: typeof AuthSignInIndexRoute
  AuthSignUpIndexRoute: typeof AuthSignUpIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orgs/': {
      id: '/dashboard/orgs/'
      path: '/orgs'
      fullPath: '/dashboard/orgs'
      preLoaderRoute: typeof DashboardOrgsIndexRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/auth/sign-up/': {
      id: '/auth/sign-up/'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in/': {
      id: '/auth/sign-in/'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/orgs/$slug': {
      id: '/dashboard/orgs/$slug'
      path: '/orgs/$slug'
      fullPath: '/dashboard/orgs/$slug'
      preLoaderRoute: typeof DashboardOrgsSlugLayoutRouteImport
      parentRoute: typeof DashboardLayoutRoute
    }
    '/dashboard/orgs/$slug/': {
      id: '/dashboard/orgs/$slug/'
      path: '/'
      fullPath: '/dashboard/orgs/$slug/'
      preLoaderRoute: typeof DashboardOrgsSlugIndexRouteImport
      parentRoute: typeof DashboardOrgsSlugLayoutRoute
    }
    '/dashboard/orgs/$slug/settings/': {
      id: '/dashboard/orgs/$slug/settings/'
      path: '/settings'
      fullPath: '/dashboard/orgs/$slug/settings'
      preLoaderRoute: typeof DashboardOrgsSlugSettingsIndexRouteImport
      parentRoute: typeof DashboardOrgsSlugLayoutRoute
    }
    '/dashboard/orgs/$slug/projects/': {
      id: '/dashboard/orgs/$slug/projects/'
      path: '/projects'
      fullPath: '/dashboard/orgs/$slug/projects'
      preLoaderRoute: typeof DashboardOrgsSlugProjectsIndexRouteImport
      parentRoute: typeof DashboardOrgsSlugLayoutRoute
    }
    '/dashboard/orgs/$slug/posts/': {
      id: '/dashboard/orgs/$slug/posts/'
      path: '/posts'
      fullPath: '/dashboard/orgs/$slug/posts'
      preLoaderRoute: typeof DashboardOrgsSlugPostsIndexRouteImport
      parentRoute: typeof DashboardOrgsSlugLayoutRoute
    }
    '/dashboard/orgs/$slug/members/': {
      id: '/dashboard/orgs/$slug/members/'
      path: '/members'
      fullPath: '/dashboard/orgs/$slug/members'
      preLoaderRoute: typeof DashboardOrgsSlugMembersIndexRouteImport
      parentRoute: typeof DashboardOrgsSlugLayoutRoute
    }
    '/dashboard/orgs/$slug/integrations/': {
      id: '/dashboard/orgs/$slug/integrations/'
      path: '/integrations'
      fullPath: '/dashboard/orgs/$slug/integrations'
      preLoaderRoute: typeof DashboardOrgsSlugIntegrationsIndexRouteImport
      parentRoute: typeof DashboardOrgsSlugLayoutRoute
    }
    '/dashboard/orgs/$slug/posts/create-posts/': {
      id: '/dashboard/orgs/$slug/posts/create-posts/'
      path: '/posts/create-posts'
      fullPath: '/dashboard/orgs/$slug/posts/create-posts'
      preLoaderRoute: typeof DashboardOrgsSlugPostsCreatePostsIndexRouteImport
      parentRoute: typeof DashboardOrgsSlugLayoutRoute
    }
  }
}

interface DashboardOrgsSlugLayoutRouteChildren {
  DashboardOrgsSlugIndexRoute: typeof DashboardOrgsSlugIndexRoute
  DashboardOrgsSlugIntegrationsIndexRoute: typeof DashboardOrgsSlugIntegrationsIndexRoute
  DashboardOrgsSlugMembersIndexRoute: typeof DashboardOrgsSlugMembersIndexRoute
  DashboardOrgsSlugPostsIndexRoute: typeof DashboardOrgsSlugPostsIndexRoute
  DashboardOrgsSlugProjectsIndexRoute: typeof DashboardOrgsSlugProjectsIndexRoute
  DashboardOrgsSlugSettingsIndexRoute: typeof DashboardOrgsSlugSettingsIndexRoute
  DashboardOrgsSlugPostsCreatePostsIndexRoute: typeof DashboardOrgsSlugPostsCreatePostsIndexRoute
}

const DashboardOrgsSlugLayoutRouteChildren: DashboardOrgsSlugLayoutRouteChildren =
  {
    DashboardOrgsSlugIndexRoute: DashboardOrgsSlugIndexRoute,
    DashboardOrgsSlugIntegrationsIndexRoute:
      DashboardOrgsSlugIntegrationsIndexRoute,
    DashboardOrgsSlugMembersIndexRoute: DashboardOrgsSlugMembersIndexRoute,
    DashboardOrgsSlugPostsIndexRoute: DashboardOrgsSlugPostsIndexRoute,
    DashboardOrgsSlugProjectsIndexRoute: DashboardOrgsSlugProjectsIndexRoute,
    DashboardOrgsSlugSettingsIndexRoute: DashboardOrgsSlugSettingsIndexRoute,
    DashboardOrgsSlugPostsCreatePostsIndexRoute:
      DashboardOrgsSlugPostsCreatePostsIndexRoute,
  }

const DashboardOrgsSlugLayoutRouteWithChildren =
  DashboardOrgsSlugLayoutRoute._addFileChildren(
    DashboardOrgsSlugLayoutRouteChildren,
  )

interface DashboardLayoutRouteChildren {
  DashboardOrgsSlugLayoutRoute: typeof DashboardOrgsSlugLayoutRouteWithChildren
  DashboardOrgsIndexRoute: typeof DashboardOrgsIndexRoute
}

const DashboardLayoutRouteChildren: DashboardLayoutRouteChildren = {
  DashboardOrgsSlugLayoutRoute: DashboardOrgsSlugLayoutRouteWithChildren,
  DashboardOrgsIndexRoute: DashboardOrgsIndexRoute,
}

const DashboardLayoutRouteWithChildren = DashboardLayoutRoute._addFileChildren(
  DashboardLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardLayoutRoute: DashboardLayoutRouteWithChildren,
  AuthSignInIndexRoute: AuthSignInIndexRoute,
  AuthSignUpIndexRoute: AuthSignUpIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
